sonar.projectKey=Infomaniak_ios-calendar
sonar.organization=infomaniak

sonar.sources=Calendar,CalendarCore,CalendarCoreUI,CalendarFeatures
sonar.exclusions=CalendarResources,Scripts,Tuist,Project.swift,Debug-Frameworks,Derived